name: Publish API docs

on: [push, pull_request, workflow_dispatch]

env:
  HADDOCK_DIR: haddock-html

jobs:

  haddock:
    runs-on: ubuntu-20.04
    steps:

    - name: Set up haskell
      uses: haskell/actions/setup@v2
      with:
        ghc-version: '9.2.7'
        cabal-version: '3.6.2.0'

    - name: Checkout repository content
      uses: actions/checkout@v3

    - name: Prepare cabal
      run: cabal update

    - name: Generate haddock API docs
      run: cabal haddock --builddir=haddock_build --haddock-hyperlinked-source --haddock-html-location='https://hackage.haskell.org/package/$pkg-$version/docs'

    - name: Find generated HTML
      run: mv $(find haddock_build -wholename '*doc/html/libro-backend' | head -n 1) $HADDOCK_DIR

    - name: Store generated API docs
      uses: actions/upload-pages-artifact@v2
      with:
        path: ${{ env.HADDOCK_DIR }}

  deploy:
    needs: haddock
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-20.04
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
