name: Build and test

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:

    - name: Set up LibreOffice
      run: |
        sudo apt update
        sudo apt install -y libreoffice libexpat1-dev libbz2-dev

    - name: Set up haskell
      uses: haskell/actions/setup@v2
      with:
        ghc-version: '9.2.7'
        cabal-version: '3.6.2.0'

    - name: Checkout repository content
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests --enable-benchmarks

    - name: Build project
      run: cabal build --enable-tests --enable-benchmarks all

    - name: Run tests
      run: cabal test --test-show-details=streaming
